FROM ubuntu:latest AS ubuntu-base
ENV DEBIAN_FRONTEND noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Build image with Python and Node.
FROM ubuntu-base AS ubuntu-with-bash

# Install required tools.
RUN apt-get -qq update \
    && apt-get -qq --no-install-recommends install ca-certificates curl \
    && curl -fsSL https://deb.nodesource.com/setup_21.x | bash - \
    && apt-get install -y nodejs \
    && apt-get -qq clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
RUN chmod 777 /app
WORKDIR /app

RUN echo "Downloading Node dependencies"
RUN mkdir /app/frontend
WORKDIR /app/frontend
ADD ./frontend/package.json ./
ADD ./frontend/package-lock.json ./
RUN npm install

RUN echo "Copying frontend files"
ADD ./frontend/public ./public
ADD ./frontend/src ./src
ADD ./frontend/*.json ./
ADD ./frontend/index.html ./
ADD ./frontend/*.ts ./
ADD ./frontend/.env ./

# Setup default command and/or parameters.
EXPOSE 5173
CMD ["npm", "run", "dev"]